In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv("movies_metadata.csv")

C:\Users\SHYAM\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df[df['id']=='1997-08-20']

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1997-08-20,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df0=pd.read_csv("credits.csv")

In [6]:
df['release_date']=pd.to_datetime(df['release_date'],errors='coerce')

In [7]:
df['release_date'][0]

Timestamp('1995-10-30 00:00:00')

In [8]:
df.release_date.value_counts().sort_index()

1874-12-09    1
1878-06-14    1
1883-11-19    1
1887-08-18    1
1888-01-01    1
             ..
2018-04-04    1
2018-04-25    1
2018-11-07    1
2018-12-31    1
2020-12-16    1
Name: release_date, Length: 17333, dtype: int64

In [9]:
df['release_date']=df['release_date'].dt.year

In [10]:
df1=df[['genres','id','release_date','title']]

In [11]:
df1=df1[df1["release_date"]==2017]

In [12]:
df1['id']=df1['id'].astype('int')

In [13]:
df1.head(5)

,genres,id,release_date,title
26560,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,2017.0,Pirates of the Caribbean: Dead Men Tell No Tales
26561,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,2017.0,Justice League
26565,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,2017.0,Thor: Ragnarok
26566,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,2017.0,Guardians of the Galaxy Vol. 2
30536,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,2017.0,The King's Daughter

In [14]:
new_df=pd.merge(df0,df1)

In [15]:
new_df.shape

(531, 6)

In [16]:
(new_df.reset_index()).shape

(531, 7)

In [17]:
new_df["cast"][0]

'[{\'cast_id\': 1, \'character\': \'Captain Jack Sparrow\', \'credit_id\': \'52fe4c9cc3a36847f8236a53\', \'gender\': 2, \'id\': 85, \'name\': \'Johnny Depp\', \'order\': 0, \'profile_path\': \'/kbWValANhZI8rbWZXximXuMN4UN.jpg\'}, {\'cast_id\': 9, \'character\': \'Captain Armando Salazar\', \'credit_id\': \'54db4949c3a368122d0017fe\', \'gender\': 2, \'id\': 3810, \'name\': \'Javier Bardem\', \'order\': 1, \'profile_path\': \'/grBOK7Ep09JBE3H5LyV5JaZZ1XZ.jpg\'}, {\'cast_id\': 16, \'character\': \'Captain Hector Barbossa\', \'credit_id\': \'54e44e5ec3a368454b00a02f\', \'gender\': 2, \'id\': 118, \'name\': \'Geoffrey Rush\', \'order\': 2, \'profile_path\': \'/5h91WHSK80YtqTk1bMiar2IZzO2.jpg\'}, {\'cast_id\': 7, \'character\': \'Henry Turner\', \'credit_id\': \'54db49359251415a0d0012a0\', \'gender\': 2, \'id\': 1017347, \'name\': \'Brenton Thwaites\', \'order\': 3, \'profile_path\': \'/dM0m0OxREfW4HxwV2qQeitS8dfO.jpg\'}, {\'cast_id\': 8, \'character\': \'Carina Smyth\', \'credit_id\': \'54db493e925141618f00189a\', \'gender\': 1, \'id\': 115150, \'name\': \'Kaya Scodelario\', \'order\': 4, \'profile_path\': \'/iTrPnn7oS96k0iWPzNxaKCNutB6.jpg\'}, {\'cast_id\': 14, \'character\': \'Joshamee Gibbs\', \'credit_id\': \'54e44e31c3a368087b004b56\', \'gender\': 2, \'id\': 2449, \'name\': \'Kevin McNally\', \'order\': 5, \'profile_path\': \'/fIJF3TZn8ckHkcl44oX77GvPv9e.jpg\'}, {\'cast_id\': 15, \'character\': \'Scrum\', \'credit_id\': \'54e44e4fc3a3684897002c08\', \'gender\': 2, \'id\': 1115, \'name\': \'Stephen Graham\', \'order\': 6, \'profile_path\': \'/81VZiCA6w8nXG0UjqXCgSJare5N.jpg\'}, {\'cast_id\': 28, \'character\': \'Scarfield\', \'credit_id\': \'57f68ea49251413616007300\', \'gender\': 2, \'id\': 1371, \'name\': \'David Wenham\', \'order\': 7, \'profile_path\': \'/xDUXLTF5i2fYx7eSEAR3IdaUb9y.jpg\'}, {\'cast_id\': 13, \'character\': \'Shansa\', \'credit_id\': \'54e44e0cc3a3685756009e87\', \'gender\': 1, \'id\': 229932, \'name\': \'Golshifteh Farahani\', \'order\': 8, \'profile_path\': \'/lbsd2lAIQq4egOUXDIfjhte12vv.jpg\'}, {\'cast_id\': 17, \'character\': \'Will Turner\', \'credit_id\': \'554768e292514119e00065f8\', \'gender\': 2, \'id\': 114, \'name\': \'Orlando Bloom\', \'order\': 9, \'profile_path\': \'/kKWJlX2tcjqceSfUxnV7Jle5Kt.jpg\'}, {\'cast_id\': 18, \'character\': \'Marty\', \'credit_id\': \'554769499251411147001bcb\', \'gender\': 2, \'id\': 4030, \'name\': \'Martin Klebba\', \'order\': 10, \'profile_path\': \'/amlhUrXQ7t1NEPajdj2dQdbC0rt.jpg\'}, {\'cast_id\': 23, \'character\': \'Mullroy\', \'credit_id\': \'57e2922bc3a36808b900c1a3\', \'gender\': 2, \'id\': 1714, \'name\': \'Angus Barnett\', \'order\': 11, \'profile_path\': \'/usYsWRccdM4Y00RycsQFFOdNVe.jpg\'}, {\'cast_id\': 19, \'character\': \'Cremble\', \'credit_id\': \'55476961c3a3680ce80091da\', \'gender\': 0, \'id\': 1193833, \'name\': \'Adam Brown\', \'order\': 12, \'profile_path\': \'/54iHvIA8ZTNfvKpb2ZxRY73A5MZ.jpg\'}, {\'cast_id\': 38, \'character\': \'Bollard\', \'credit_id\': \'57f68ea7925141360100754f\', \'gender\': 0, \'id\': 1355191, \'name\': \'Danny Kirrane\', \'order\': 13, \'profile_path\': \'/vn4NIHMJb0Sf39MOP3cgMdk2N8h.jpg\'}, {\'cast_id\': 22, \'character\': \'Murtogg\', \'credit_id\': \'57e29210c3a3680a110056ca\', \'gender\': 0, \'id\': 1713, \'name\': \'Giles New\', \'order\': 14, \'profile_path\': \'/e0Ap9fkLAFcxLVHpK8KH2TQV3wI.jpg\'}, {\'cast_id\': 84, \'character\': \'Pike\', \'credit_id\': \'591f7a46c3a368723d03b63b\', \'gender\': 0, \'id\': 1819920, \'name\': \'Delroy Atkinson\', \'order\': 15, \'profile_path\': \'/XcMnuXUPLNYzRL58s5TKPUFq2g.jpg\'}, {\'cast_id\': 21, \'character\': \'Uncle Jack\', \'credit_id\': \'57e291cf92514118f700625d\', \'gender\': 2, \'id\': 10215, \'name\': \'Paul McCartney\', \'order\': 16, \'profile_path\': \'/v7FagbD9EY4MVUtcrk9ESjPWV7q.jpg\'}, {\'cast_id\': 43, \'character\': \'Elizabeth Swann\', \'credit_id\': \'58f708cf9251415dec00953a\', \'gender\': 1, \'id\': 116, \'name\': \'Keira Knightley\', \'order\': 17, \'profile_path\': \'/rv6quYbTgFTmBAoePwy5xuurW3g.jpg\'}, {\'cast_id\': 91, \'character\': \'Young Jack Sparrow\', \'credit_id\': \'59338b3dc3a3685a35016ca6\', \'gender\': 0, \'id\': 1772106, \'name\': \'Anthony De La Torre\', \'order\': 18, \'profile_path\': \'/sgtspl6fcAuhPo4wKYkzlzSgvmg.jpg\'}, {\'cast_id\': 92, \'character\': \'Young Henry Turner\', \'credit_id\': \'59338b66c3a36859de01633a\', \'gender\': 2, \'id\': 1828139, \'name\': \'Lewis McGowan\', \'order\': 19, \'profile_path\': \'/27pyhArCRR8ZqIyiak9c0N0l1nz.jpg\'}, {\'cast_id\': 85, \'character\': \'Lieutenant Lesaro\', \'credit_id\': \'591f7a8cc3a368799b037a0a\', \'gender\': 2, \'id\': 1089049, \'name\': \'Juan Carlos Vellido\', \'order\': 20, \'profile_path\': \'/m1GEfFgcDNPTCTGUhrita7d5ec1.jpg\'}, {\'cast_id\': 86, \'character\': \'Officer Madga\', \'credit_id\': \'591f7acc925141482f039128\', \'gender\': 0, \'id\': 1530814, \'name\': \'Rodney Afif\', \'order\': 21, \'profile_path\': \'/wr1gTOcRcyKO4fYlUwsPLRlP7bn.jpg\'}, {\'cast_id\': 87, \'character\': \'Mayor Dix\', \'credit_id\': \'591f7ae1c3a3687a64039857\', \'gender\': 2, \'id\': 27752, \'name\': \'Bruce Spence\', \'order\': 22, \'profile_path\': \'/pwJJBmO9MG3OxVX9efGrB6BTFyw.jpg\'}, {\'cast_id\': 31, \'character\': "Mayor\'s Wife", \'credit_id\': \'57f68ea5c3a3681607006e8c\', \'gender\': 1, \'id\': 61914, \'name\': \'Zoe Ventoura\', \'order\': 23, \'profile_path\': \'/fMBiXCtCTqpEmjAfTVC3NssVMCk.jpg\'}, {\'cast_id\': 33, \'character\': \'Maddox\', \'credit_id\': \'57f68ea6c3a3681607006e8e\', \'gender\': 2, \'id\': 1112872, \'name\': \'James Mackay\', \'order\': 24, \'profile_path\': \'/nJPYaP94wXwh1bYnFzkQh1BB30l.jpg\'}, {\'cast_id\': 51, \'character\': \'Upper Class Lady\', \'credit_id\': \'591293c59251414edb04e228\', \'gender\': 1, \'id\': 1813772, \'name\': \'Brooke Chamberlain\', \'order\': 25, \'profile_path\': \'/vYqTEUUY4EG6jPzP5wnZNhy4aAy.jpg\'}, {\'cast_id\': 45, \'character\': \'Young Captain Teague\', \'credit_id\': \'5912926dc3a368646b0521a2\', \'gender\': 2, \'id\': 16811, \'name\': \'Alexander Scheer\', \'order\': 26, \'profile_path\': \'/f6eWj5VEMBb3O3aviqgMoujM3kf.jpg\'}, {\'cast_id\': 32, \'character\': \'Pirate Broom\', \'credit_id\': \'57f68ea5925141360d007429\', \'gender\': 0, \'id\': 61784, \'name\': \'Goran D. Kleut\', \'order\': 27, \'profile_path\': \'/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg\'}, {\'cast_id\': 40, \'character\': \'Pirate\', \'credit_id\': \'57f68ea892514136130074b0\', \'gender\': 0, \'id\': 1535048, \'name\': \'Wassim Hawat\', \'order\': 28, \'profile_path\': \'/yTJCBoDa1OKt7h6JDKYaZnlLqeA.jpg\'}, {\'cast_id\': 37, \'character\': \'British Executioner\', \'credit_id\': \'57f68ea7925141360100754d\', \'gender\': 0, \'id\': 1394235, \'name\': "Ben O\'Toole", \'order\': 29, \'profile_path\': \'/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg\'}, {\'cast_id\': 42, \'character\': \'Young Pirate Jeff\', \'credit_id\': \'57f68ea8c3a368161c007391\', \'gender\': 2, \'id\': 1690240, \'name\': \'Finn Ireland\', \'order\': 30, \'profile_path\': \'/x1IZJZLFHboPhZbdycZcNo2kZoM.jpg\'}, {\'cast_id\': 44, \'character\': \'Spanish Officer\', \'credit_id\': \'59129248c3a36864ec048639\', \'gender\': 0, \'id\': 1414764, \'name\': \'Nico Cortez\', \'order\': 31, \'profile_path\': \'/ujk9vAlutbLUe9VbjPE6RDuQqVC.jpg\'}, {\'cast_id\': 49, \'character\': \'Young Greenhorn\', \'credit_id\': \'591293549251414eca04accf\', \'gender\': 0, \'id\': 1394227, \'name\': \'James Fraser\', \'order\': 32, \'profile_path\': \'/4lcpUIRwFVmPkkxUvYdUNSQQddc.jpg\'}, {\'cast_id\': 115, \'character\': \'Woman\', \'credit_id\': \'59c783a3c3a368140305a3f1\', \'gender\': 0, \'id\': 1499792, \'name\': \'Derani Scarr\', \'order\': 33, \'profile_path\': \'/aob0mfWTaJaUlHDVef2dA7Dlwhc.jpg\'}, {\'cast_id\': 93, \'character\': \'Grimes\', \'credit_id\': \'5999d18a9251414a18001dd4\', \'gender\': 0, \'id\': 126200, \'name\': \'Robert Morgan\', \'order\': 34, \'profile_path\': \'/8sFiiilQmp2jvLKn6h5QPchA5Gq.jpg\'}, {\'cast_id\': 94, \'character\': \'Pirate with Broom\', \'credit_id\': \'59a67afe9251411293009e0c\', \'gender\': 0, \'id\': 61784, \'name\': \'Goran D. Kleut\', \'order\': 35, \'profile_path\': \'/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg\'}, {\'cast_id\': 29, \'character\': \'Spanish Soldier\', \'credit_id\': \'57f68ea5925141360100754a\', \'gender\': 2, \'id\': 1386458, \'name\': \'Mahesh Jadu\', \'order\': 36, \'profile_path\': \'/gfcZiYji4x3tjGQq7vTK8goz40D.jpg\'}, {\'cast_id\': 34, \'character\': \'British Soldier\', \'credit_id\': \'57f68ea692514136130074ae\', \'gender\': 0, \'id\': 1394427, \'name\': \'Travis Jeffery\', \'order\': 37, \'profile_path\': \'/lOR40uoh60aKx3ORArhKBQAaBO6.jpg\'}, {\'cast_id\': 111, \'character\': \'British Soldier\', \'credit_id\': \'59c77df0c3a36813ed057ad8\', \'gender\': 0, \'id\': 1205492, \'name\': \'Akos Armont\', \'order\': 38, \'profile_path\': \'/t0nRw07H8aXtzz7az5yjDSZwVVg.jpg\'}, {\'cast_id\': 104, \'character\': \'British Soldier\', \'credit_id\': \'59c6c742c3a368141e044fa3\', \'gender\': 0, \'id\': 1533328, \'name\': \'Sean Lynch\', \'order\': 39, \'profile_path\': \'/m8Q9SaYTWJ5iXLoS2E4zvcD4tQ1.jpg\'}, {\'cast_id\': 95, \'character\': \'British Soldier\', \'credit_id\': \'59a67b84c3a36827990085f8\', \'gender\': 0, \'id\': 1394235, \'name\': "Ben O\'Toole", \'order\': 40, \'profile_path\': \'/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg\'}, {\'cast_id\': 105, \'character\': \'CG Ghost Soldier\', \'credit_id\': \'59c6c7d69251415b32049e77\', \'gender\': 0, \'id\': 1893668, \'name\': \'Akshay Caplash\', \'order\': 41, \'profile_path\': \'/s3QTX4IdN3wUNN9YiZBid2ANhmM.jpg\'}, {\'cast_id\': 106, \'character\': \'CG Ghost Soldier\', \'credit_id\': \'59c6c8629251415b6e047778\', \'gender\': 2, \'id\': 1893671, \'name\': \'Rafael Torrijos\', \'order\': 42, \'profile_path\': \'/lro1QSBv5cmkiO8R8RbxADGXIka.jpg\'}, {\'cast_id\': 112, \'character\': \'CG Ghost Soldier\', \'credit_id\': \'59c7805d9251415b87053e7f\', \'gender\': 0, \'id\': 1893872, \'name\': \'Mivon Prince-Leyva\', \'order\': 43, \'profile_path\': \'/c5CfJBn3B0Ce07TxgPUx9ttUTLv.jpg\'}, {\'cast_id\': 110, \'character\': \'First Officer Wade\', \'credit_id\': \'59c77d9cc3a3681454052a75\', \'gender\': 2, \'id\': 76068, \'name\': \'Michael Dorman\', \'order\': 44, \'profile_path\': \'/95hvX99zyHIpHJ9Ajv35TWgNlGN.jpg\'}, {\'cast_id\': 116, \'character\': \'Officer Cole\', \'credit_id\': \'59c784a99251415b870541ed\', \'gender\': 2, \'id\': 33184, \'name\': \'Rohan Nichol\', \'order\': 45, \'profile_path\': \'/nzvL3MRpADYWlH4ppyYgmCnM1kZ.jpg\'}, {\'cast_id\': 96, \'character\': \'Officer Santos\', \'credit_id\': \'59c6b999c3a368144304be34\', \'gender\': 0, \'id\': 1893640, \'name\': \'Rupert Raineri\', \'order\': 46, \'profile_path\': \'/oXeONe2M6qwiVlDFpJIT1wrA9Ek.jpg\'}, {\'cast_id\': 97, \'character\': \'Officer Moss\', \'credit_id\': \'59c6b9fec3a368143004b954\', \'gender\': 0, \'id\': 1893641, \'name\': \'Stephen Lopez\', \'order\': 47, \'profile_path\': \'/hYoItjKNWnncBbjM3voLEu5DnN8.jpg\'}, {\'cast_id\': 109, \'character\': \'Captain Toms\', \'credit_id\': \'59c77d659251415b5d05482d\', \'gender\': 0, \'id\': 75744, \'name\': \'Richard Piper\', \'order\': 48, \'profile_path\': \'/3SEI2j8jIzVthrYifpMgjNC4MHp.jpg\'}, {\'cast_id\': 98, \'character\': \'Mr. Krill\', \'credit_id\': \'59c6bc1dc3a368140304c936\', \'gender\': 0, \'id\': 1347909, \'name\': \'Justin Smith\', \'order\': 49, \'profile_path\': \'/7knG8VrDuEmhAZT2B4p1zmMjDJy.jpg\'}, {\'cast_id\': 99, \'character\': \'Mr. Swift\', \'credit_id\': \'59c6be5f9251415b2804b325\', \'gender\': 0, \'id\': 1486057, \'name\': \'John Leary\', \'order\': 50, \'profile_path\': \'/bCP5mcXgFp5X7mq7jTmYpmBbtHE.jpg\'}, {\'cast_id\': 100, \'character\': \'Bowen\', \'credit_id\': \'59c6c070c3a368141e0448fa\', \'gender\': 0, \'id\': 1014587, \'name\': \'Bryan Probets\', \'order\': 51, \'profile_path\': \'/wp0o01OuR5YF3DWjBBUYAWUbzHA.jpg\'}, {\'cast_id\': 113, \'character\': \'Pig Kelly\', \'credit_id\': \'59c7810a9251415b240582b0\', \'gender\': 2, \'id\': 57904, \'name\': \'Ken Radley\', \'order\': 52, \'profile_path\': \'/jqiM2DbXtNRF3yxRaU2nkYzewEJ.jpg\'}, {\'cast_id\': 101, \'character\': \'Beatrice\', \'credit_id\': \'59c6c14bc3a36813ed04aed4\', \'gender\': 1, \'id\': 1252521, \'name\': \'Hannah Walters\', \'order\': 53, \'profile_path\': \'/3hUokXHcRhdpM971cb3kbaVSrY8.jpg\'}, {\'cast_id\': 114, \'character\': \'Priest\', \'credit_id\': \'59c7826c9251415b32055db4\', \'gender\': 0, \'id\': 1545346, \'name\': \'Jonathan Elsom\', \'order\': 54, \'profile_path\': \'/i1LEAdB5y6zg4lVa01hV9ZZo7Ew.jpg\'}, {\'cast_id\': 102, \'character\': \'Captain Morgan\', \'credit_id\': \'59c6c217c3a3681454046e90\', \'gender\': 2, \'id\': 143328, \'name\': \'K. Todd Freeman\', \'order\': 55, \'profile_path\': \'/2L7Qh4hA2dsCIPZAVfgerax7i2q.jpg\'}, {\'cast_id\': 107, \'character\': \'Jail Guard\', \'credit_id\': \'59c6c957c3a368140304d946\', \'gender\': 0, \'id\': 1893677, \'name\': \'James Lawson\', \'order\': 56, \'profile_path\': \'/gtcdsTruLPzpL2xJhePsOq38LjX.jpg\'}, {\'cast_id\': 108, \'character\': "Uncle Jack\'s Cellmate", \'credit_id\': \'59c6ca34c3a3681461041481\', \'gender\': 0, \'id\': 1216570, \'name\': \'Darcy Laurie\', \'order\': 57, \'profile_path\': \'/bTZgOB4wl4ECbHiGjoKQAQdvTUW.jpg\'}, {\'cast_id\': 30, \'character\': \'Townswoman (uncredited)\', \'credit_id\': \'57f68ea592514172c5002e01\', \'gender\': 1, \'id\': 1255055, \'name\': \'Jessica Green\', \'order\': 58, \'profile_path\': \'/7l3bkNv92uii8im5B4vyF0ABgcS.jpg\'}, {\'cast_id\': 52, \'character\': \'Townswoman (uncredited)\', \'credit_id\': \'591294019251414e8504da81\', \'gender\': 0, \'id\': 1345090, \'name\': \'Haley Madison\', \'order\': 59, \'profile_path\': \'/3XJGp5oJCGvqosOhSSgQZWI8cKo.jpg\'}, {\'cast_id\': 36, \'character\': \'Townschild (uncredited)\', \'credit_id\': \'57f68ea7c3a36816250071ea\', \'gender\': 0, \'id\': 1632129, \'name\': \'Kiara Freeman\', \'order\': 60, \'profile_path\': \'/3n5EDxHBritMzqxIS47A6Qccg74.jpg\'}, {\'cast_id\': 35, \'character\': \'Townschild (uncredited)\', \'credit_id\': \'57f68ea6c3a3681604007202\', \'gender\': 0, \'id\': 1690237, \'name\': \'Piper Nairn\', \'order\': 61, \'profile_path\': \'/cOVpgx5JF9XeFUF2am9Bk4f5wkh.jpg\'}, {\'cast_id\': 53, \'character\': \'Townsperson (uncredited)\', \'credit_id\': \'5912942ec3a36864c604d3d7\', \'gender\': 1, \'id\': 1692989, \'name\': \'Suzanne Dervish-Ali\', \'order\': 62, \'profile_path\': \'/7OQgHuuzFbtO9jAF4w6zcuzqmAK.jpg\'}, {\'cast_id\': 50, \'character\': \'Townsperson (uncredited)\', \'credit_id\': \'591293a5c3a368650a04aff2\', \'gender\': 0, \'id\': 1813771, \'name\': \'Donnie Baxter\', \'order\': 63, \'profile_path\': \'/dm2cSQwySnOj9sWqca9nBspS8sL.jpg\'}, {\'cast_id\': 41, \'character\': \'Maid (uncredited)\', \'credit_id\': \'57f68ea8925141360300747b\', \'gender\': 0, \'id\': 1690239, \'name\': \'Winnie Mzembe\', \'order\': 64, \'profile_path\': \'/lUTozzeBvTZZkpUQLE5V5baS12X.jpg\'}, {\'cast_id\': 39, \'character\': \'Greenwich Village Upper Class Lady (uncredited)\', \'credit_id\': \'57f68ea892514172c5002e04\', \'gender\': 0, \'id\': 1690238, \'name\': \'Christie-Lee Britten\', \'order\': 65, \'profile_path\': \'/uNSjA73XjDbQMJB1XGnoKB89zux.jpg\'}, {\'cast_id\': 48, \'character\': \'Twin Middle Class Lady (uncredited)\', \'credit_id\': \'5912932f9251414e8904ee64\', \'gender\': 0, \'id\': 1813770, \'name\': \'Mollie McGregor\', \'order\': 66, \'profile_path\': \'/q4XZ9rV1TbrsqvK91a9FAMudL6C.jpg\'}, {\'cast_id\': 103, \'character\': \'Twin Middle Class Lady (uncredited)\', \'credit_id\': \'59c6c5399251415b6e0473ea\', \'gender\': 0, \'id\': 1571654, \'name\': \'Sophia McGregor\', \'order\': 67, \'profile_path\': \'/egbKVmd3f1xgAq90vDiRLLZIFXx.jpg\'}]'

In [18]:
new_df['cast']=new_df['cast'].apply(lambda x: eval(x))

new_df['crew']=new_df['crew'].apply(lambda x: eval(x))


new_df['genres']=new_df['genres'].apply(lambda x: eval(x))

In [19]:
def evaluate_genres(x):
    gem=[]
    sep=" "
    for i in x:
        if (i.get("name")=="Science Fiction"):
            
            gem.append("Sci-Fi")
        else:
            gem.append(i.get("name"))
            
    if (gem==[]):
        return np.NaN
    else:
            
        return (sep.join(gem))

In [20]:
new_df['genres']=new_df['genres'].apply(lambda x:evaluate_genres(x))

In [21]:
new_df['genres']

0      Adventure Action Fantasy Comedy
1      Action Adventure Fantasy Sci-Fi
2      Action Adventure Fantasy Sci-Fi
3       Action Adventure Comedy Sci-Fi
4             Fantasy Action Adventure
                    ...
526                     Romance Comedy
527         Crime Comedy Action Family
528    Family Animation Romance Comedy
529               Crime Drama Thriller
530                                NaN
Name: genres, Length: 531, dtype: object

In [22]:
def actor(x,n):
    cast=[]
    sep=" "
    for i in x:
        cast.append(i.get("name"))
    if(n==1):        
        if (cast==[]):
            return np.NaN
        else:
            return (cast[0])
    elif(n==2):
        if (len(x)<=1):
            return np.NaN
        else:
            return (cast[1])
    else:    
        if (len(x)<=2):
            return np.NaN
        else:
            return (cast[2])

In [23]:
new_df['actor_1_name']=new_df["cast"].apply(lambda x:actor(x,1))

In [24]:

new_df['actor_2_name']=new_df["cast"].apply(lambda x:actor(x,2))
new_df['actor_3_name']=new_df["cast"].apply(lambda x:actor(x,3))

In [25]:
new_df

,cast,crew,id,genres,release_date,title,actor_1_name,actor_2_name,actor_3_name
0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",166426,Adventure Action Fantasy Comedy,2017.0,Pirates of the Caribbean: Dead Men Tell No Tales,Johnny Depp,Javier Bardem,Geoffrey Rush
1,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",141052,Action Adventure Fantasy Sci-Fi,2017.0,Justice League,Ben Affleck,Henry Cavill,Gal Gadot
2,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",284053,Action Adventure Fantasy Sci-Fi,2017.0,Thor: Ragnarok,Chris Hemsworth,Tom Hiddleston,Cate Blanchett
3,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",283995,Action Adventure Comedy Sci-Fi,2017.0,Guardians of the Galaxy Vol. 2,Chris Pratt,Zoe Saldana,Dave Bautista
4,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",245842,Fantasy Action Adventure,2017.0,The King's Daughter,Pierce Brosnan,William Hurt,Benjamin Walker
...,...,...,...,...,...,...,...,...,...
526,"[{'cast_id': 0, 'character': 'Satu', 'credit_i...","[{'credit_id': '597e22f69251415d7801c74a', 'de...",468707,Romance Comedy,2017.0,Thick Lashes of Lauri Mäntyvaara,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala
527,"[{'cast_id': 0, 'character': 'Detective Simmon...","[{'credit_id': '593ba0c29251410593009be3', 'de...",461297,Crime Comedy Action Family,2017.0,Cop and a Half: New Recruit,Lou Diamond Phillips,Wallace Shawn,Gina Holden
528,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de...",455661,Family Animation Romance Comedy,2017.0,In a Heartbeat,NaN,NaN,NaN
529,"[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...",404604,Crime Drama Thriller,2017.0,Mom,Sridevi Kapoor,Sajal Ali,Akshaye Khanna
530,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257,NaN,2017.0,Queerama,NaN,NaN,NaN

In [26]:
def director(x):
    sep=" "
    dirr=[]
    for i in x:
        if(i.get("job")=="Director"):
            dirr.append(i.get("name"))
            
    if  (dirr==[]) :
        return np.NaN
    else:
        return (sep.join(dirr))

In [27]:
new_df["director_name"]=new_df["crew"].apply(lambda x:director(x))

In [28]:
new_df

,cast,crew,id,genres,release_date,title,actor_1_name,actor_2_name,actor_3_name,director_name
0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",166426,Adventure Action Fantasy Comedy,2017.0,Pirates of the Caribbean: Dead Men Tell No Tales,Johnny Depp,Javier Bardem,Geoffrey Rush,Joachim Rønning Espen Sandberg
1,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",141052,Action Adventure Fantasy Sci-Fi,2017.0,Justice League,Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder
2,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",284053,Action Adventure Fantasy Sci-Fi,2017.0,Thor: Ragnarok,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi
3,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",283995,Action Adventure Comedy Sci-Fi,2017.0,Guardians of the Galaxy Vol. 2,Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn
4,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",245842,Fantasy Action Adventure,2017.0,The King's Daughter,Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara
...,...,...,...,...,...,...,...,...,...,...
526,"[{'cast_id': 0, 'character': 'Satu', 'credit_i...","[{'credit_id': '597e22f69251415d7801c74a', 'de...",468707,Romance Comedy,2017.0,Thick Lashes of Lauri Mäntyvaara,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Hannaleena Hauru
527,"[{'cast_id': 0, 'character': 'Detective Simmon...","[{'credit_id': '593ba0c29251410593009be3', 'de...",461297,Crime Comedy Action Family,2017.0,Cop and a Half: New Recruit,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Jonathan A. Rosenbaum
528,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de...",455661,Family Animation Romance Comedy,2017.0,In a Heartbeat,NaN,NaN,NaN,Beth David Esteban Bravo
529,"[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...",404604,Crime Drama Thriller,2017.0,Mom,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Ravi Udyawar
530,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257,NaN,2017.0,Queerama,NaN,NaN,NaN,Daisy Asquith

In [29]:
new_df=new_df[['genres','title','actor_1_name','actor_2_name','actor_3_name','director_name']]

In [30]:
new_df

,genres,title,actor_1_name,actor_2_name,actor_3_name,director_name
0,Adventure Action Fantasy Comedy,Pirates of the Caribbean: Dead Men Tell No Tales,Johnny Depp,Javier Bardem,Geoffrey Rush,Joachim Rønning Espen Sandberg
1,Action Adventure Fantasy Sci-Fi,Justice League,Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder
2,Action Adventure Fantasy Sci-Fi,Thor: Ragnarok,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi
3,Action Adventure Comedy Sci-Fi,Guardians of the Galaxy Vol. 2,Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn
4,Fantasy Action Adventure,The King's Daughter,Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara
...,...,...,...,...,...,...
526,Romance Comedy,Thick Lashes of Lauri Mäntyvaara,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Hannaleena Hauru
527,Crime Comedy Action Family,Cop and a Half: New Recruit,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Jonathan A. Rosenbaum
528,Family Animation Romance Comedy,In a Heartbeat,NaN,NaN,NaN,Beth David Esteban Bravo
529,Crime Drama Thriller,Mom,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Ravi Udyawar
530,NaN,Queerama,NaN,NaN,NaN,Daisy Asquith

In [31]:
new_df.isna().sum()

genres            7
title             0
actor_1_name     22
actor_2_name     55
actor_3_name     70
director_name     4
dtype: int64

In [32]:
new_df.dropna(how="any",inplace=True)

C:\Users\SHYAM\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [33]:
new_df.rename(columns={"title":"movie_title"},inplace=True)

C:\Users\SHYAM\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [34]:
new_df['comb']=new_df["movie_title"]+" "+new_df["actor_1_name"]+" "+new_df["actor_2_name"]+" "+new_df["actor_3_name"]+" "+new_df["director_name"]+" "+new_df["genres"]

C:\Users\SHYAM\AppData\Local\Temp/ipykernel_13288/1266834223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['comb']=new_df["movie_title"]+" "+new_df["actor_1_name"]+" "+new_df["actor_2_name"]+" "+new_df["actor_3_name"]+" "+new_df["director_name"]+" "+new_df["genres"]

In [35]:
new_df

,genres,movie_title,actor_1_name,actor_2_name,actor_3_name,director_name,comb
0,Adventure Action Fantasy Comedy,Pirates of the Caribbean: Dead Men Tell No Tales,Johnny Depp,Javier Bardem,Geoffrey Rush,Joachim Rønning Espen Sandberg,Pirates of the Caribbean: Dead Men Tell No Tal...
1,Action Adventure Fantasy Sci-Fi,Justice League,Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder,Justice League Ben Affleck Henry Cavill Gal Ga...
2,Action Adventure Fantasy Sci-Fi,Thor: Ragnarok,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi,Thor: Ragnarok Chris Hemsworth Tom Hiddleston ...
3,Action Adventure Comedy Sci-Fi,Guardians of the Galaxy Vol. 2,Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn,Guardians of the Galaxy Vol. 2 Chris Pratt Zoe...
4,Fantasy Action Adventure,The King's Daughter,Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara,The King's Daughter Pierce Brosnan William Hur...
...,...,...,...,...,...,...,...
524,Romance Comedy,The Incredible Jessica James,Jessica Williams,Chris O'Dowd,Keith Stanfield,Jim Strouse,The Incredible Jessica James Jessica Williams ...
525,Romance,Can't Buy My Love,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Farhad Mann,Can't Buy My Love Adelaide Kane Benjamin Holli...
526,Romance Comedy,Thick Lashes of Lauri Mäntyvaara,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Hannaleena Hauru,Thick Lashes of Lauri Mäntyvaara Inka Haapamäk...
527,Crime Comedy Action Family,Cop and a Half: New Recruit,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Jonathan A. Rosenbaum,Cop and a Half: New Recruit Lou Diamond Philli...
529,Crime Drama Thriller,Mom,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Ravi Udyawar,Mom Sridevi Kapoor Sajal Ali Akshaye Khanna Ra...

In [43]:
df_2016=pd.read_csv("df_2016.csv")

In [45]:
df=df_2016.append(new_df)

In [47]:
df.to_csv("Finaldata.csv",index=False)